# Form implementation generated from reading ui file '.\view\WidgetFileSelector.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(653, 36)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        Form.setFont(font)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnOpen = QtWidgets.QPushButton(parent=Form)
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout_3.addWidget(self.btnOpen)
        self.frameProcess = QtWidgets.QFrame(parent=Form)
        self.frameProcess.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameProcess.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameProcess.setObjectName("frameProcess")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameProcess)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelFilename = QtWidgets.QLabel(parent=self.frameProcess)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFilename.sizePolicy().hasHeightForWidth())
        self.labelFilename.setSizePolicy(sizePolicy)
        self.labelFilename.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.labelFilename.setObjectName("labelFilename")
        self.horizontalLayout.addWidget(self.labelFilename)
        self.btnContinue = QtWidgets.QToolButton(parent=self.frameProcess)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/action/images/vswin2019/Run_16x.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnContinue.setIcon(icon)
        self.btnContinue.setAutoRaise(True)
        self.btnContinue.setObjectName("btnContinue")
        self.horizontalLayout.addWidget(self.btnContinue)
        self.btnStop = QtWidgets.QToolButton(parent=self.frameProcess)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/action/images/vswin2019/Stop_16x.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnStop.setIcon(icon1)
        self.btnStop.setAutoRaise(True)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        self.horizontalLayout_3.addWidget(self.frameProcess)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnOpen.setText(_translate("Form", "Open..."))
        self.labelFilename.setText(_translate("Form", "Select a *.dmp core dump file in Minidump format to debug"))
        self.btnContinue.setText(_translate("Form", "Continue"))
        self.btnStop.setText(_translate("Form", "Stop"))
